using LogicalOptimizer.Benchmarks;
using Xunit;

namespace LogicalOptimizer.Tests;

/// <summary>
///     Regression suite over the vendored multi-output PLA corpus
///     (LogicalOptimizer.Benchmarks/PlaCorpus, generated by <see cref="PlaCorpusGenerator" />;
///     competitive-assessment gap #3, 30-day roadmap item 1). Every output function of every
///     PLA is optimized through the facade and the suite asserts, deterministically and
///     gate-visibly (no Category=Performance — the corpus is small on purpose):
///     <list type="number">
///         <item>the equivalence self-check passes (the guard, not just the absence of a crash);</item>
///         <item>the result is <c>MinimalProven</c> (all members are inside the ≤ 10-variable exact zone);</item>
///         <item>the optimized literal count never exceeds the raw cube-expansion literal count;</item>
///         <item>
///             the optimized literal count equals the PINNED golden value — the actual
///             regression signal: a future minimizer change that produces a larger (or
///             different) cover for any output fails here;
///         </item>
///         <item>per file, the TOTAL literal count across all outputs matches the pinned sum
///             (the multi-output collective view);</item>
///         <item>the committed corpus files are byte-identical to the deterministic generator
///             output (regenerate with
///             <c>dotnet run -c Release --project LogicalOptimizer.Benchmarks -- generate-corpora</c>).</item>
///     </list>
/// </summary>
/// <remarks>
///     In <see cref="TimeSensitiveCollection" /> because the dense 8-input member runs close
///     to the facade's 10 s wall-clock cap when CPU-starved by the parallel gate.
/// </remarks>
[Collection(TimeSensitiveCollection.Name)]
public class PlaCorpusRegressionTests
{
    /// <summary>
    ///     Pinned golden table: optimized literal count per PLA output, as measured by the
    ///     facade on the committed corpus (see PlaCorpus/README.md for the full table).
    ///     Update only after a reviewed, intentional minimizer change.
    /// </summary>
    public static TheoryData<string, string, int> GoldenOutputLiterals => new()
    {
        { "bcd7seg.pla", "sa", 9 },
        { "bcd7seg.pla", "sb", 8 },
        { "bcd7seg.pla", "sc", 5 },
        { "bcd7seg.pla", "sd", 12 },
        { "bcd7seg.pla", "se", 5 },
        { "bcd7seg.pla", "sf", 8 },
        { "bcd7seg.pla", "sg", 9 },
        { "add2.pla", "cout", 7 },
        { "add2.pla", "s1", 12 },
        { "add2.pla", "s0", 4 },
        { "dec3to8.pla", "y0", 3 },
        { "dec3to8.pla", "y1", 3 },
        { "dec3to8.pla", "y2", 3 },
        { "dec3to8.pla", "y3", 3 },
        { "dec3to8.pla", "y4", 3 },
        { "dec3to8.pla", "y5", 3 },
        { "dec3to8.pla", "y6", 3 },
        { "dec3to8.pla", "y7", 3 },
        { "prio8.pla", "v", 8 },
        { "prio8.pla", "y2", 4 },
        { "prio8.pla", "y1", 6 },
        { "prio8.pla", "y0", 7 },
        { "cmp3.pla", "lt", 11 },
        { "cmp3.pla", "eq", 12 },
        { "cmp3.pla", "gt", 11 },
        { "rnd6x4-01.pla", "f0", 22 },
        { "rnd6x4-01.pla", "f1", 19 },
        { "rnd6x4-01.pla", "f2", 24 },
        { "rnd6x4-01.pla", "f3", 32 },
        { "rnd6x4-02.pla", "f0", 21 },
        { "rnd6x4-02.pla", "f1", 22 },
        { "rnd6x4-02.pla", "f2", 21 },
        { "rnd6x4-02.pla", "f3", 18 },
        { "rnd8x3-01.pla", "f0", 54 },
        { "rnd8x3-01.pla", "f1", 48 },
        { "rnd8x3-01.pla", "f2", 62 }
    };

    /// <summary>Pinned totals across all outputs of a file: (cube-expansion, optimized).</summary>
    public static TheoryData<string, int, int> GoldenFileTotals => new()
    {
        { "bcd7seg.pla", 196, 56 },
        { "add2.pla", 88, 23 },
        { "dec3to8.pla", 24, 24 },
        { "prio8.pla", 76, 25 },
        { "cmp3.pla", 384, 34 },
        { "rnd6x4-01.pla", 258, 97 },
        { "rnd6x4-02.pla", 214, 82 },
        { "rnd8x3-01.pla", 318, 164 }
    };

    [Theory]
    [MemberData(nameof(GoldenOutputLiterals))]
    public void Output_OptimizedViaFacade_IsEquivalentAndAtPinnedLiteralCount(
        string fileName, string outputName, int pinnedLiterals)
    {
        var pla = LoadPla(fileName);
        var output = IndexOfOutput(pla, outputName);
        var cubeExpansionLiterals = pla.OutputCubeLiteralCount(output);

        var result = new BooleanExpressionOptimizer().OptimizeExpression(pla.OutputExpression(output));

        // The guard itself: the optimized form is PROVEN equivalent to the cube expansion.
        Assert.True(result.IsEquivalent(),
            $"{fileName}/{outputName}: equivalence self-check failed for '{result.Optimized}'");

        // Every corpus member has <= 8 inputs, inside the exact-minimization guarantee zone.
        Assert.Equal(MinimizationStatus.MinimalProven, result.MinimizationStatus);

        var optimizedLiterals = AstMetrics.CountLiterals(new FormulaFactory().Parse(result.Optimized));
        Assert.True(optimizedLiterals <= cubeExpansionLiterals,
            $"{fileName}/{outputName}: optimizer made the function LARGER " +
            $"({cubeExpansionLiterals} -> {optimizedLiterals} literals)");
        Assert.Equal(pinnedLiterals, optimizedLiterals);
    }

    [Theory]
    [MemberData(nameof(GoldenFileTotals))]
    public void File_TotalLiteralsAcrossAllOutputs_MatchPinnedTable(
        string fileName, int pinnedCubeExpansionTotal, int pinnedOptimizedTotal)
    {
        var pla = LoadPla(fileName);
        var optimizer = new BooleanExpressionOptimizer();
        var factory = new FormulaFactory();

        var cubeExpansionTotal = 0;
        var optimizedTotal = 0;
        for (var output = 0; output < pla.OutputNames.Count; output++)
        {
            cubeExpansionTotal += pla.OutputCubeLiteralCount(output);
            var result = optimizer.OptimizeExpression(pla.OutputExpression(output));
            optimizedTotal += AstMetrics.CountLiterals(factory.Parse(result.Optimized));
        }

        Assert.Equal(pinnedCubeExpansionTotal, cubeExpansionTotal);
        Assert.Equal(pinnedOptimizedTotal, optimizedTotal);
    }

    [Fact]
    public void Corpus_CommittedFiles_MatchTheDeterministicGeneratorExactly()
    {
        var directory = CorpusDirectory();
        Assert.True(directory != null && Directory.Exists(directory),
            "PLA corpus directory missing. Regenerate with " +
            "'dotnet run -c Release --project LogicalOptimizer.Benchmarks -- generate-corpora'.");

        var expected = PlaCorpusGenerator.Generate();
        var committed = Directory.EnumerateFiles(directory!, "*.pla")
            .Select(Path.GetFileName).OrderBy(n => n, StringComparer.Ordinal).ToList();
        Assert.Equal(expected.Select(i => i.FileName).OrderBy(n => n, StringComparer.Ordinal), committed);

        foreach (var instance in expected)
        {
            var onDisk = File.ReadAllText(Path.Combine(directory!, instance.FileName));
            Assert.Equal(instance.Content.ReplaceLineEndings("\n"), onDisk.ReplaceLineEndings("\n"));
        }
    }

    [Fact]
    public void Corpus_EveryOutputOfEveryFile_HasAPinnedGoldenRow()
    {
        // The golden table cannot silently fall out of sync with the corpus: adding or
        // renaming an output without pinning its literal count fails here.
        var pinned = GoldenOutputLiterals.Select(row => ((string)row[0], (string)row[1])).ToHashSet();
        foreach (var instance in PlaCorpusGenerator.Generate())
        {
            var pla = PlaFile.Parse(instance.Content);
            foreach (var output in pla.OutputNames)
                Assert.Contains((instance.FileName, output), pinned);
        }

        Assert.Equal(pinned.Count,
            PlaCorpusGenerator.Generate().Sum(i => PlaFile.Parse(i.Content).OutputNames.Count));
    }

    private static PlaFile LoadPla(string fileName)
    {
        var directory = CorpusDirectory()
                        ?? throw new InvalidOperationException("PLA corpus directory not found");
        return PlaFile.Read(Path.Combine(directory, fileName));
    }

    private static int IndexOfOutput(PlaFile pla, string outputName)
    {
        for (var i = 0; i < pla.OutputNames.Count; i++)
            if (pla.OutputNames[i] == outputName)
                return i;
        throw new InvalidOperationException($"Output '{outputName}' not found");
    }

    /// <summary>Corpus directory used at test time: output copy if present, else the source tree.</summary>
    private static string? CorpusDirectory()
    {
        var output = Path.Combine(AppContext.BaseDirectory, "PlaCorpus");
        if (Directory.Exists(output) && Directory.EnumerateFiles(output, "*.pla").Any())
            return output;
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "LogicalOptimizer.sln")))
            directory = directory.Parent;
        return directory == null
            ? null
            : Path.Combine(directory.FullName, "LogicalOptimizer.Benchmarks", "PlaCorpus");
    }
}
