#!/usr/bin/env bash
# Roadmap P0.2 — #SAT competitor adapter (d4 / c2d) for the cross-library comparison
# (BDD / d-DNNF table). Runs each DIMACS through the external exact model counters
# under one identical per-function timeout and prints a Markdown column of model
# count + time. SELF-SKIPS a counter that is not on PATH and NEVER fabricates a
# number.
#
# It does NOT run automatically; run it where d4/c2d are installed.
#
# Usage:
#   tools/comparison/run_modelcount_competitors.sh <dimacs-dir> [timeout-seconds]
#
# SEMANTICS: the DIMACS emitted by `comparison-suite --emit-sat-dimacs` are the
# equivalence MITERS (all UNSAT ⇒ model count 0). To compare #SAT head-to-head
# against the BDD/d-DNNF `modelCount` in our-results.json you must count the
# per-function CNF, not the miter — see tools/comparison/README.md. This adapter
# shows the invocation + parsing and applies the shared timeout.
set -euo pipefail

DIMACS_DIR="${1:?usage: run_modelcount_competitors.sh <dimacs-dir> [timeout-seconds]}"
TIMEOUT="${2:-10}"

if [[ ! -d "$DIMACS_DIR" ]]; then
  echo "# DIMACS dir '$DIMACS_DIR' not found. Emit it with 'comparison-suite --emit-sat-dimacs'." >&2
  exit 1
fi

have() { command -v "$1" >/dev/null 2>&1; }

COUNTERS=()
have d4  && COUNTERS+=("d4")
have c2d && COUNTERS+=("c2d")

if [[ ${#COUNTERS[@]} -eq 0 ]]; then
  echo "# NOTE: neither d4 nor c2d is on PATH; #SAT competitor columns stay 'pending'." >&2
  echo "# Install a counter and re-run to fill them. No numbers fabricated." >&2
  exit 0
fi

echo "<!-- generated by tools/comparison/run_modelcount_competitors.sh; counters: ${COUNTERS[*]}; timeout ${TIMEOUT}s -->"
printf '| Function |'; for c in "${COUNTERS[@]}"; do printf ' %s #SAT | %s ms |' "$c" "$c"; done; printf '\n'
printf '|----------|'; for _ in "${COUNTERS[@]}"; do printf '%s' '-----:|-----:|'; done; printf '\n'

# d4 prints `s <count>`; c2d prints a "Counting... N models" style line. Both are
# parsed leniently; a timeout (exit 124) is recorded as `timeout`.
run_one() {
  local counter="$1" cnf="$2"
  local start end rc out count
  start=$(date +%s.%N)
  set +e
  case "$counter" in
    # d4v2 counts only with an explicit method flag (-mc); a bare `d4 <file>` just prints
    # benchmark info and exits without a count. It writes the result as `s <count>`.
    d4)  out=$(timeout "${TIMEOUT}s" d4 -mc "$cnf" 2>/dev/null) ;;
    c2d) out=$(timeout "${TIMEOUT}s" c2d -in "$cnf" 2>/dev/null) ;;
  esac
  rc=$?
  set -e
  end=$(date +%s.%N)
  if [[ $rc -eq 124 ]]; then echo "timeout|>${TIMEOUT}s"; return; fi
  count=$(grep -Eo '[0-9]+' <<<"$(grep -Ei 'models|^s ' <<<"$out" | tail -1)" | tail -1)
  printf '%s|%.3f\n' "${count:-unknown}" "$(echo "($end - $start) * 1000" | bc -l)"
}

for cnf in "$DIMACS_DIR"/*.cnf; do
  [[ -e "$cnf" ]] || { echo "# no *.cnf in $DIMACS_DIR" >&2; break; }
  name=$(basename "$cnf" .cnf); name=${name%.miter}
  row="| $name |"
  for c in "${COUNTERS[@]}"; do
    IFS='|' read -r n t < <(run_one "$c" "$cnf")
    row+=" $n | $t |"
  done
  echo "$row"
done
