#!/usr/bin/env python3
"""Roadmap P0.2 — Z3 SAT competitor adapter for the cross-library comparison (Table 3).

Solves each equivalence-miter DIMACS (``comparison-suite --emit-sat-dimacs``) with Z3's
solver under one identical per-function timeout and prints a Markdown column of verdict +
time keyed by function name — the same shape the CaDiCaL / Kissat shell adapter emits, so
the merge treats Z3 as one more SAT column. Every miter is expected UNSAT (⇒ the
optimization is equivalence-preserving); a ``sat`` would signal a real bug.

SELF-SKIPS cleanly if the ``z3`` module is not importable and NEVER fabricates a number:
a solve that exceeds the budget is ``timeout`` (Z3 returns ``unknown``), never a failure.

Usage:
    python tools/comparison/run_z3_competitor.py <dimacs-dir> [timeout-seconds]
"""
from __future__ import annotations

import glob
import os
import sys
import time


def try_import_z3():
    try:
        import z3  # noqa: F401
        return z3
    except Exception:
        return None


def read_clauses(path):
    """Yield each DIMACS clause as a list of non-zero ints (skipping c/p lines)."""
    clauses = []
    with open(path, "r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if not line or line[0] in ("c", "p"):
                continue
            lits = [int(tok) for tok in line.split() if tok != "0"]
            if lits:
                clauses.append(lits)
    return clauses


def solve(z3, path, timeout_seconds):
    """Return (verdict, ms) for the miter CNF, or ('timeout', ...) past the budget."""
    clauses = read_clauses(path)
    solver = z3.Solver()
    solver.set("timeout", int(timeout_seconds * 1000))
    variables = {}

    def lit(value):
        name = abs(value)
        var = variables.get(name)
        if var is None:
            var = z3.Bool(f"v{name}")
            variables[name] = var
        return var if value > 0 else z3.Not(var)

    for clause in clauses:
        solver.add(z3.Or([lit(v) for v in clause]))

    start = time.perf_counter()
    result = solver.check()
    elapsed_ms = (time.perf_counter() - start) * 1000.0
    # z3.CheckSatResult is unhashable, so compare rather than dict-dispatch.
    if result == z3.unsat:
        verdict = "unsat"
    elif result == z3.sat:
        verdict = "sat"
    else:
        verdict = "timeout"
    return verdict, elapsed_ms


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        print("usage: run_z3_competitor.py <dimacs-dir> [timeout-seconds]", file=sys.stderr)
        return 2
    dimacs_dir = argv[0]
    timeout_seconds = float(argv[1]) if len(argv) >= 2 else 20.0

    if not os.path.isdir(dimacs_dir):
        print(f"# DIMACS dir '{dimacs_dir}' not found. Emit it with "
              "'comparison-suite --emit-sat-dimacs'.", file=sys.stderr)
        return 1

    z3 = try_import_z3()
    if z3 is None:
        print("# NOTE: the z3 module is not importable here; Z3 column stays 'pending'. "
              "Install via `pip install z3-solver`. No numbers fabricated.", file=sys.stderr)
        return 0

    version = ".".join(str(n) for n in z3.get_version())
    print(f"<!-- generated by tools/comparison/run_z3_competitor.py; z3 {version}; "
          f"timeout {timeout_seconds:g}s -->")
    print("| Function | Z3 verdict | Z3 ms |")
    print("|----------|:----------:|------:|")

    for cnf in sorted(glob.glob(os.path.join(dimacs_dir, "*.miter.cnf"))):
        name = os.path.basename(cnf)[: -len(".miter.cnf")]
        try:
            verdict, ms = solve(z3, cnf, timeout_seconds)
            time_cell = f">{timeout_seconds:g}s" if verdict == "timeout" else f"{ms:.3f}"
        except Exception as exc:  # pragma: no cover - per-instance robustness
            print(f"# z3 failed on '{name}': {exc}", file=sys.stderr)
            verdict, time_cell = "error", "-"
        print(f"| {name} | {verdict} | {time_cell} |")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
