#!/usr/bin/env bash
# Roadmap P0.2 — SAT competitor adapter (CaDiCaL / Kissat) for the cross-library
# comparison. Runs each equivalence-miter DIMACS through the external SAT solvers
# under one identical per-function timeout and prints a Markdown column of
# verdict + time. SELF-SKIPS any solver that is not on PATH and NEVER fabricates a
# number — mirroring the OUR harness leaving competitor cells `pending`.
#
# It does NOT run automatically; run it where cadical/kissat are installed.
#
# Usage:
#   tools/comparison/run_sat_competitors.sh <dimacs-dir> [timeout-seconds]
#
# Produce <dimacs-dir> first with:
#   dotnet run -c Release --project LogicalOptimizer.Benchmarks -- \
#     comparison-suite --emit-sat-dimacs <dimacs-dir>
set -euo pipefail

DIMACS_DIR="${1:?usage: run_sat_competitors.sh <dimacs-dir> [timeout-seconds]}"
TIMEOUT="${2:-10}"

if [[ ! -d "$DIMACS_DIR" ]]; then
  echo "# DIMACS dir '$DIMACS_DIR' not found. Emit it with 'comparison-suite --emit-sat-dimacs'." >&2
  exit 1
fi

have() { command -v "$1" >/dev/null 2>&1; }

SOLVERS=()
have cadical && SOLVERS+=("cadical")
have kissat  && SOLVERS+=("kissat")

if [[ ${#SOLVERS[@]} -eq 0 ]]; then
  echo "# NOTE: neither cadical nor kissat is on PATH; SAT competitor columns stay 'pending'." >&2
  echo "# Install a solver and re-run to fill them. No numbers fabricated." >&2
  exit 0
fi

echo "<!-- generated by tools/comparison/run_sat_competitors.sh; solvers: ${SOLVERS[*]}; timeout ${TIMEOUT}s -->"
printf '| Function |'; for s in "${SOLVERS[@]}"; do printf ' %s verdict | %s ms |' "$s" "$s"; done; printf '\n'
printf '|----------|'; for _ in "${SOLVERS[@]}"; do printf '---------:|---------:|'; done; printf '\n'

# Parse a DRAT-capable solver's stdout. `s SATISFIABLE` / `s UNSATISFIABLE`; a
# timeout (killed by `timeout`, exit 124) is recorded as `timeout`, never a failure.
run_one() {
  local solver="$1" cnf="$2"
  local start end verdict rc
  start=$(date +%s.%N)
  set +e
  out=$(timeout "${TIMEOUT}s" "$solver" "$cnf" 2>/dev/null)
  rc=$?
  set -e
  end=$(date +%s.%N)
  if [[ $rc -eq 124 ]]; then
    echo "timeout|>${TIMEOUT}s"
    return
  fi
  if   grep -q '^s UNSATISFIABLE' <<<"$out"; then verdict="unsat"
  elif grep -q '^s SATISFIABLE'   <<<"$out"; then verdict="sat"
  else verdict="unknown"; fi
  printf '%s|%.3f\n' "$verdict" "$(echo "($end - $start) * 1000" | bc -l)"
}

for cnf in "$DIMACS_DIR"/*.miter.cnf; do
  [[ -e "$cnf" ]] || { echo "# no *.miter.cnf in $DIMACS_DIR" >&2; break; }
  name=$(basename "$cnf" .miter.cnf)
  row="| $name |"
  for s in "${SOLVERS[@]}"; do
    IFS='|' read -r v t < <(run_one "$s" "$cnf")
    row+=" $v | $t |"
  done
  echo "$row"
done
