using System.Diagnostics;
using Xunit;
using Xunit.Abstractions;

namespace LogicalOptimizer.Tests;

/// <summary>
///     Performance-regression suite over the vendored SATLIB-STYLE SAT corpus
///     (LogicalOptimizer.Benchmarks/SatCorpus, generated by <see cref="SatCorpusGenerator" />).
///     Every instance is solved under a fixed, DETERMINISTIC conflict budget and the suite
///     asserts CORRECTNESS UNDER BUDGET — the real regression signal — not wall-clock time
///     (doc/TESTING.md Part 2, rule 4). Timings are logged for human inspection only.
///     Whole class is <c>Category=Performance</c>, so it is excluded from the PR gate and
///     runs in the nightly <c>sat-benchmarks.yml</c> job. Run locally with:
///     <c>dotnet test --filter "Category=Performance"</c>.
/// </summary>
public class SatCorpusRegressionTests
{
    /// <summary>
    ///     Deterministic effort budget. Sized (with margin) so every vendored instance —
    ///     including the pigeonhole PHP(8→7) case, the hardest for CDCL — reaches a
    ///     definite verdict; a future change that makes the solver need MORE than this to
    ///     decide a corpus instance is exactly the regression this suite exists to catch.
    /// </summary>
    private const int MaxConflicts = 5_000_000;

    /// <summary>Below this variable count an UNSAT verdict is re-confirmed by 2^n brute force.</summary>
    private const int BruteForceVariableLimit = 20;

    private readonly ITestOutputHelper _output;

    public SatCorpusRegressionTests(ITestOutputHelper output)
    {
        _output = output;
    }

    public static IEnumerable<object[]> CorpusFiles()
    {
        var directory = CorpusDirectory();
        if (directory == null || !Directory.Exists(directory)) yield break;
        foreach (var path in Directory.EnumerateFiles(directory, "*.cnf")
                     .OrderBy(p => Path.GetFileName(p), StringComparer.Ordinal))
            yield return new object[] { Path.GetFileName(path) };
    }

    [Theory]
    [Trait("Category", "Performance")]
    [MemberData(nameof(CorpusFiles))]
    public void Corpus_ResolvesToExpectedVerdictUnderBudget(string fileName)
    {
        var directory = CorpusDirectory()
                        ?? throw new InvalidOperationException("SAT corpus directory not found");
        var instance = DimacsCnf.Read(Path.Combine(directory, fileName));

        var solver = new SatSolver(instance.VariableCount);
        foreach (var clause in instance.Clauses) solver.AddClause(clause);

        var stopwatch = Stopwatch.StartNew();
        var verdict = solver.Solve(MaxConflicts);
        stopwatch.Stop();

        // Logged for human inspection only — NEVER asserted on (rule 4: no wall-clock gating)
        _output.WriteLine(
            $"{fileName,-18} verdict={verdict,-13} conflicts={solver.ConflictCount,8} " +
            $"time={stopwatch.ElapsedMilliseconds,6} ms  vars={instance.VariableCount} clauses={instance.Clauses.Count}");

        var expected = instance.ExpectedSatisfiable ? SatResult.Satisfiable : SatResult.Unsatisfiable;

        // Correctness under budget: the budget must suffice AND the verdict must be right
        Assert.NotEqual(SatResult.Unknown, verdict);
        Assert.Equal(expected, verdict);

        if (instance.ExpectedSatisfiable)
            // Independent oracle: the returned model must satisfy every clause of the CNF
            Assert.All(instance.Clauses, clause =>
                Assert.Contains(clause, literal => solver.GetValue(Math.Abs(literal)) == literal > 0));
        else if (instance.VariableCount <= BruteForceVariableLimit)
            // Independent oracle: exhaustively confirm no satisfying assignment exists
            Assert.False(SatTestOracles.BruteForceSatisfiable(instance.VariableCount,
                instance.Clauses.ToList()));
    }

    [Fact]
    [Trait("Category", "Performance")]
    public void Corpus_HasTheExpectedShape()
    {
        var directory = CorpusDirectory();
        Assert.True(directory != null && Directory.Exists(directory),
            "SAT corpus directory missing. Regenerate with LOGICALOPTIMIZER_REGENERATE_SATCORPUS=1.");

        var files = Directory.EnumerateFiles(directory!, "*.cnf").Select(Path.GetFileName).ToList();
        var sat = files.Count(f => f!.StartsWith("uf", StringComparison.Ordinal) &&
                                   !f.StartsWith("uuf", StringComparison.Ordinal));
        var unsat = files.Count(f => f!.StartsWith("uuf", StringComparison.Ordinal));

        Assert.Equal(SatCorpusGenerator.Generate().Count, files.Count);
        Assert.Equal(10, sat);
        Assert.Equal(10, unsat);

        // Each committed file's recorded 'expected' header must match its uf/uuf prefix
        foreach (var file in files)
        {
            var expectedSat = !file!.StartsWith("uuf", StringComparison.Ordinal);
            var instance = DimacsCnf.Read(Path.Combine(directory!, file));
            Assert.Equal(expectedSat, instance.ExpectedSatisfiable);
        }
    }

    /// <summary>
    ///     One-time (re)generation of the vendored corpus into the SOURCE tree. No-op unless
    ///     <c>LOGICALOPTIMIZER_REGENERATE_SATCORPUS=1</c>, so it is inert in normal runs.
    ///     Run: <c>LOGICALOPTIMIZER_REGENERATE_SATCORPUS=1 dotnet test --filter
    ///     FullyQualifiedName~RegenerateCorpus</c> and review/commit the diff.
    /// </summary>
    [Fact]
    public void RegenerateCorpus_WhenRequested()
    {
        if (Environment.GetEnvironmentVariable("LOGICALOPTIMIZER_REGENERATE_SATCORPUS") != "1")
            return;

        var target = SourceCorpusDirectory();
        Directory.CreateDirectory(target);
        foreach (var instance in SatCorpusGenerator.Generate())
            File.WriteAllText(Path.Combine(target, instance.FileName),
                instance.Dimacs.ReplaceLineEndings("\n"));
    }

    /// <summary>Corpus directory used at test time: output copy if present, else the source tree.</summary>
    private static string? CorpusDirectory()
    {
        var output = Path.Combine(AppContext.BaseDirectory, "SatCorpus");
        if (Directory.Exists(output) && Directory.EnumerateFiles(output, "*.cnf").Any())
            return output;
        var source = TrySourceCorpusDirectory();
        return source != null && Directory.Exists(source) ? source : null;
    }

    private static string SourceCorpusDirectory()
    {
        return TrySourceCorpusDirectory()
               ?? throw new InvalidOperationException("Cannot locate the repository root (LogicalOptimizer.sln)");
    }

    private static string? TrySourceCorpusDirectory()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "LogicalOptimizer.sln")))
            directory = directory.Parent;
        return directory == null
            ? null
            : Path.Combine(directory.FullName, "LogicalOptimizer.Benchmarks", "SatCorpus");
    }
}
