package org.logicng.comparison;

import java.io.BufferedReader;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.SortedSet;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.logicng.formulas.Formula;
import org.logicng.formulas.FormulaFactory;
import org.logicng.formulas.Variable;
import org.logicng.io.parsers.PropositionalParser;
import org.logicng.knowledgecompilation.bdds.BDD;
import org.logicng.knowledgecompilation.bdds.BDDFactory;
import org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel;

/**
 * Roadmap P0.2 — LogicNG BDD competitor adapter. Reads the shared comparison corpus
 * (the SAME {@code tools/comparison_corpus.txt} the OUR-side harness consumes), compiles
 * each function to a BDD with LogicNG, and prints a GitHub-Markdown column of node count
 * and exact model count keyed by function name. It applies one identical per-function
 * timeout (methodology: single runner, identical timeout) and NEVER fabricates a number:
 * a function that errors or times out gets an honest {@code error} / {@code timeout} cell.
 *
 * <p>The model count is over the function's variables, directly comparable to the
 * {@code modelCount} column of {@code our-results.json} (BDD / d-DNNF #SAT).</p>
 *
 * <p>Usage: {@code java -jar logicng-adapter.jar <corpus-path> [timeout-seconds]}</p>
 */
public final class Main {

    private static final int BDD_NODE_TABLE = 1_000_000;
    private static final int BDD_CACHE = 100_000;

    public static void main(final String[] args) throws IOException {
        if (args.length < 1) {
            System.err.println("usage: java -jar logicng-adapter.jar <corpus-path> [timeout-seconds]");
            System.exit(2);
            return;
        }
        final String corpusPath = args[0];
        final long timeoutSeconds = args.length >= 2 ? Long.parseLong(args[1]) : 20L;

        final List<String[]> functions = readCorpus(corpusPath);
        if (functions.isEmpty()) {
            System.err.println("# Corpus '" + corpusPath + "' contained no functions.");
            return;
        }

        System.out.println("<!-- generated by tools/comparison/logicng (LogicNG 2.4.1); timeout "
                + timeoutSeconds + "s -->");
        System.out.println("| Function | LogicNG nodes | LogicNG #SAT | LogicNG ms |");
        System.out.println("|----------|-------------:|------------:|----------:|");

        final ExecutorService executor = Executors.newSingleThreadExecutor();
        try {
            for (final String[] fn : functions) {
                final String name = fn[1];
                final String expression = fn[2].replace("!", "~");
                final Result r = measure(executor, expression, timeoutSeconds);
                System.out.println("| " + name + " | " + r.nodes + " | " + r.modelCount + " | " + r.ms + " |");
            }
        } finally {
            executor.shutdownNow();
        }
    }

    private static Result measure(final ExecutorService executor, final String expression,
                                  final long timeoutSeconds) {
        final Callable<Result> task = () -> {
            final FormulaFactory f = new FormulaFactory();
            final PropositionalParser parser = new PropositionalParser(f);
            final Formula formula = parser.parse(expression);
            final SortedSet<Variable> variables = formula.variables();
            final List<Variable> ordering = new ArrayList<>(variables);
            final long start = System.nanoTime();
            final BDDKernel kernel = ordering.isEmpty()
                    ? new BDDKernel(f, 0, BDD_NODE_TABLE, BDD_CACHE)
                    : new BDDKernel(f, ordering, BDD_NODE_TABLE, BDD_CACHE);
            final BDD bdd = BDDFactory.build(formula, kernel);
            final BigInteger modelCount = bdd.modelCount();
            final long ms = (System.nanoTime() - start) / 1_000_000L;
            return new Result(String.valueOf(bdd.nodeCount()), modelCount.toString(), String.valueOf(ms));
        };

        final Future<Result> future = executor.submit(task);
        try {
            return future.get(timeoutSeconds, TimeUnit.SECONDS);
        } catch (final TimeoutException e) {
            future.cancel(true);
            return new Result("timeout", "timeout", ">" + timeoutSeconds + "s");
        } catch (final Exception e) {
            return new Result("error", "error", "-");
        }
    }

    private static List<String[]> readCorpus(final String path) throws IOException {
        final List<String[]> functions = new ArrayList<>();
        try (BufferedReader reader = Files.newBufferedReader(Paths.get(path), StandardCharsets.UTF_8)) {
            String raw;
            while ((raw = reader.readLine()) != null) {
                final String line = raw.trim();
                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }
                final String[] parts = line.split("\\|", 3);
                if (parts.length != 3) {
                    continue;
                }
                functions.add(new String[]{parts[0].trim(), parts[1].trim(), parts[2].trim()});
            }
        }
        return functions;
    }

    private static final class Result {
        final String nodes;
        final String modelCount;
        final String ms;

        Result(final String nodes, final String modelCount, final String ms) {
            this.nodes = nodes;
            this.modelCount = modelCount;
            this.ms = ms;
        }
    }

    private Main() {
    }
}
