using LogicalOptimizer.Benchmarks;
using Xunit;

namespace LogicalOptimizer.Tests;

/// <summary>
///     Regression suite over the vendored adversarial BDD variable-order corpus
///     (LogicalOptimizer.Benchmarks/BddOrderCorpus, generated by
///     <see cref="BddOrderCorpusGenerator" />; competitive-assessment gap #3, 30-day roadmap
///     item 1). Each structure (n-bit equality comparator, Bryant's disjoint-pairs DNF) is
///     committed twice: named so the engine's default alphabetical order is the good
///     INTERLEAVED order, and named so it is the adversarial SEPARATED order (exponential
///     ROBDD). Deterministic and gate-visible, the suite pins the documented envelope:
///     <list type="number">
///         <item>with the good order the diagram builds inside a SMALL explicit node budget,
///             at a pinned allocated node count and pinned exact model count;</item>
///         <item>with the adversarial order the same small budget produces the DOCUMENTED
///             typed failure — <see cref="NodeBudgetExceededException" /> — quickly, never a
///             hang or memory blowup (the "typed budgets + honest statuses" claim);</item>
///         <item>reordering recovers: <c>BuildWithBestOrder</c>'s first-appearance heuristic
///             (the formula text keeps pairs adjacent) and <c>BuildWithSiftedOrder</c>'s
///             Rudell sifting both build a small diagram from the adversarially named file
///             under the same small budget, at pinned node counts.</item>
///     </list>
///     The corpus is generated with no randomness; a shape test asserts the committed files
///     are byte-identical to the generator (regenerate with
///     <c>dotnet run -c Release --project LogicalOptimizer.Benchmarks -- generate-corpora</c>).
/// </summary>
public class BddOrderCorpusRegressionTests
{
    /// <summary>
    ///     Deliberately small explicit budget (not the 1,000,000 default): comfortably above
    ///     every good-order build (max 259 allocated nodes) and far below every adversarial
    ///     build (min 6,138 allocated nodes), so the bad cases fail fast and the tests stay
    ///     gate-fast.
    /// </summary>
    private const int SmallNodeBudget = 1_500;

    /// <summary>Pinned per-file values: allocated nodes after Build, and exact model count.</summary>
    public static TheoryData<string, int, long> InterleavedGolden => new()
    {
        // file, pinned Build(...).NodeCount under SmallNodeBudget, pinned model count
        { "eq10-interleaved.expr", 186, 1_024 },
        { "eq12-interleaved.expr", 259, 4_096 },
        { "pairs12-interleaved.expr", 169, 16_245_775 },
        { "pairs14-interleaved.expr", 225, 263_652_487 }
    };

    public static TheoryData<string> SeparatedFiles => new()
    {
        "eq10-separated.expr",
        "eq12-separated.expr",
        "pairs12-separated.expr",
        "pairs14-separated.expr"
    };

    /// <summary>Pinned recovery values: BuildWithBestOrder node count, and exact model count.</summary>
    public static TheoryData<string, int, long> RecoveryGolden => new()
    {
        { "eq10-separated.expr", 78, 1_024 },
        { "eq12-separated.expr", 94, 4_096 },
        { "pairs12-separated.expr", 59, 16_245_775 },
        { "pairs14-separated.expr", 69, 263_652_487 }
    };

    [Theory]
    [MemberData(nameof(InterleavedGolden))]
    public void GoodOrder_BuildsInsideTheSmallBudget_AtPinnedSize(
        string fileName, int pinnedNodeCount, long pinnedModelCount)
    {
        var ast = LoadAst(fileName);

        // Default Build uses alphabetical order, which this file's naming makes interleaved.
        var bdd = BinaryDecisionDiagram.Build(ast, SmallNodeBudget);

        Assert.Equal(pinnedNodeCount, bdd.NodeCount);
        Assert.Equal(pinnedModelCount, (long)bdd.CountSatisfyingAssignments());
    }

    [Theory]
    [MemberData(nameof(SeparatedFiles))]
    public void AdversarialOrder_ExceedsTheSmallBudget_WithTheDocumentedTypedException(string fileName)
    {
        var ast = LoadAst(fileName);

        // Same function, same budget — only the (name-induced) variable order differs.
        // The documented contract is a TYPED budget failure, not a hang or memory blowup.
        var exception = Assert.Throws<NodeBudgetExceededException>(
            () => BinaryDecisionDiagram.Build(ast, SmallNodeBudget));
        Assert.Contains("node budget", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Theory]
    [MemberData(nameof(RecoveryGolden))]
    public void AdversarialOrder_IsRecoveredByTheOrderHeuristics_AtPinnedSize(
        string fileName, int pinnedNodeCount, long pinnedModelCount)
    {
        var ast = LoadAst(fileName);

        // First-appearance order (a candidate heuristic) is interleaved because the formula
        // text lists each pair together — recovery succeeds under the SAME small budget that
        // just failed the alphabetical build.
        var bdd = BinaryDecisionDiagram.BuildWithBestOrder(ast, SmallNodeBudget);

        Assert.Equal(pinnedNodeCount, bdd.NodeCount);
        Assert.Equal(pinnedModelCount, (long)bdd.CountSatisfyingAssignments());
    }

    [Fact]
    public void AdversarialOrder_SiftingCompactsFurther_ToThePinnedMinimum()
    {
        // Rudell sifting on the adversarially named 12-bit comparator: 36 reachable nodes
        // (vs 94 from the static heuristics and a >1,500-node blowup alphabetically).
        var bdd = BinaryDecisionDiagram.BuildWithSiftedOrder(LoadAst("eq12-separated.expr"), SmallNodeBudget);

        Assert.Equal(36, bdd.NodeCount);
        Assert.Equal(4_096, (long)bdd.CountSatisfyingAssignments());
    }

    [Fact]
    public void Corpus_CommittedFiles_MatchTheDeterministicGeneratorExactly()
    {
        var directory = CorpusDirectory();
        Assert.True(directory != null && Directory.Exists(directory),
            "BDD order corpus directory missing. Regenerate with " +
            "'dotnet run -c Release --project LogicalOptimizer.Benchmarks -- generate-corpora'.");

        var expected = BddOrderCorpusGenerator.Generate();
        var committed = Directory.EnumerateFiles(directory!, "*.expr")
            .Select(Path.GetFileName).OrderBy(n => n, StringComparer.Ordinal).ToList();
        Assert.Equal(expected.Select(i => i.FileName).OrderBy(n => n, StringComparer.Ordinal), committed);

        foreach (var instance in expected)
        {
            var onDisk = File.ReadAllText(Path.Combine(directory!, instance.FileName));
            Assert.Equal(instance.Content.ReplaceLineEndings("\n"), onDisk.ReplaceLineEndings("\n"));
        }
    }

    private static AstNode LoadAst(string fileName)
    {
        var directory = CorpusDirectory()
                        ?? throw new InvalidOperationException("BDD order corpus directory not found");
        var expression = BddOrderCorpusGenerator.ReadExpression(Path.Combine(directory, fileName));
        return new FormulaFactory().Parse(expression);
    }

    /// <summary>Corpus directory used at test time: output copy if present, else the source tree.</summary>
    private static string? CorpusDirectory()
    {
        var output = Path.Combine(AppContext.BaseDirectory, "BddOrderCorpus");
        if (Directory.Exists(output) && Directory.EnumerateFiles(output, "*.expr").Any())
            return output;
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "LogicalOptimizer.sln")))
            directory = directory.Parent;
        return directory == null
            ? null
            : Path.Combine(directory.FullName, "LogicalOptimizer.Benchmarks", "BddOrderCorpus");
    }
}
